name: CI

on:
  push:
    branches:
    - master

jobs:
  build_common:
    name: Build on Mac
    runs-on: macos-10.15
    steps:

      - name: common_all
        run: |

          #Pre-reqs
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          brew install node@10
          brew install fastlane
          sudo npm install -g cordova
          sudo npm install -g phonegap
          brew install git
          mkdir applications
          echo 'echo 1a:' $PWD
          #[echo 1a: /Users/runner/runners/2.165.2/work/testapp/testapp]

          cd applications
          echo 'echo 1b:' $PWD
          #[echo 1b: /Users/runner/runners/2.165.2/work/testapp/testapp/applications]

          git clone https://${{ secrets.GITHUB_REPO_TOKEN }}@github.com/badsprad/testapp.git

          # Cordova
          cd testapp
          echo 'echo 1c:' $PWD
          #[echo 1c: /Users/runner/runners/2.165.2/work/testapp/testapp/applications/testapp]

          cordova telemetry off
          CORDOVA_APP_NAME="cordova"
          CORDOVA_APP_ID="com.testapp.domain"
          cordova create $CORDOVA_APP_NAME $CORDOVA_APP_ID
          cd $CORDOVA_APP_NAME
          echo 'echo 2:' $PWD 
          #[echo 2: /Users/runner/runners/2.165.2/work/testapp/testapp/applications/testapp/cordova]
          cordova platform add ios
          #cordova platform add android

          # NPM config
          cd ..
          echo 'echo 3:' $PWD 
          #[echo 3: /Users/runner/runners/2.165.2/work/testapp/testapp/applications/testapp]
          npm install
          npm audit fix

          # Vue build
          npm run webpack-build

          # Cordova prepare, copy DIST output from Vue to Cordova
          cd $CORDOVA_APP_NAME/www
          echo 'echo 4:' $PWD
          #[echo 4: /Users/runner/runners/2.165.2/work/testapp/testapp/applications/testapp/cordova/www]
          if [ -d www ]; then
            rm -rf www
          fi
          cd ..
          echo 'echo 5:' $PWD
          #[echo 5: /Users/runner/runners/2.165.2/work/testapp/testapp/applications/testapp/cordova]
          cp -rf ../dist/. ./www
          cp -rf ../_tmp/cordova/build.json ./
          cordova prepare ios

          echo 'echo BUILD.JSON-start'
          cat build.json
          echo 'echo BUILD.JSON-end'

          # Phonegap: cloud build
          phonegap analytics off
          phonegap remote login --username ${{ secrets.PHONEGAP_USER_EMAIL }} --password ${{ secrets.PHONEGAP_USER_PASSWORD }}
          CORDOVA_TOKEN=${{ secrets.PHONEGAP_OATH_TOKEN }}
          CORDOVA_APP_ID="$(curl https://build.phonegap.com/api/v1/apps?auth_token=$CORDOVA_TOKEN | jq -r '.apps[].id')"
          if [[ $CORDOVA_APP_ID > 0 ]]
          then 
            # fix ref: https://github.com/phonegap/phonegap-cli/issues/122
            rm -f root/applications/testapp/$CORDOVA_APP_NAME/.cordova/config.json
            curl -X DELETE https://build.phonegap.com/api/v1/apps/$CORDOVA_APP_ID?auth_token=$CORDOVA_TOKEN
          fi

          # Phonegap: download iTunes IPA file
          phonegap remote run ios > capture_url.txt
          PGB_URL="$(grep -E -o '(http[s]?:\/\/)?([^\/\s]+\/)(.*)' capture_url.txt)"
          wget --user-agent=Mozilla $PGB_URL --output-document=pgb_response_ios.ipa





