name: CI

on:
  push:
    branches:
    - master

jobs:
  build_common:
    name: Build on Mac
    runs-on: macos-10.15
    steps:

      - name: common_all
        run: |

          # Pre-reqs
          cd /
          cd Users/$USER
          mkdir applications
          cd applications
          git clone https://${{ secrets.GITHUB_REPO_TOKEN }}@github.com/badsprad/testapp.git
          cd testapp

          #sudo npm install -g --unsafe-perm --allow-root
          #sudo node-gyp rebuild -g --unsafe-perm
          #sudo npm install -g node-gyp --unsafe-perm 

          sudo npm install -g n --unsafe-perm --allow-root
          n 11.15.0

          npm install
          
          sudo npm install -g cordova
          sudo npm install -g phonegap
          sudo npm install -g cordova-config-cli

          #brew install fastlane