name: CI

on:
  push:
    branches:
    - master

jobs:
  build_common:
    name: Build on Mac
    runs-on: macos-10.15
    steps:

      - name: common_all
        run: |

          #Pre-reqs
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          brew install node@10
          brew install fastlane
          sudo npm install -g cordova
          sudo npm install -g phonegap
          brew install git
          mkdir applications
          cd applications
          git clone https://${{ secrets.GITHUB_REPO_TOKEN }}@github.com/badsprad/testapp.git

          # Cordova
          cd testapp
          cordova telemetry off
          CORDOVA_APP_NAME="cordova"
          CORDOVA_APP_ID="com.testapp.domain"
          cordova create $CORDOVA_APP_NAME $CORDOVA_APP_ID
          cd $CORDOVA_APP_NAME
          cordova platform add ios
          #cordova platform add android

          # NPM config
          cd ..
          npm install
          npm audit fix

          # Vue build
          npm run webpack-build

          # Cordova prepare, copy DIST output from Vue to Cordova
          cd $CORDOVA_APP_NAME/www
          if [ -d www ]; then
            rm -rf www
          fi
          cd ..
          cp -rf ../dist/. ./www
          cp -rf ../_tmp/cordova/build.json ./
          cordova prepare ios

          # Phonegap: cloud build
          phonegap analytics off
          phonegap remote login --username ${{ secrets.PHONEGAP_USER_EMAIL }} --password ${{ secrets.PHONEGAP_USER_PASSWORD }}
          CORDOVA_TOKEN=${{ secrets.PHONEGAP_OATH_TOKEN }}
          CORDOVA_APP_ID="$(curl https://build.phonegap.com/api/v1/apps?auth_token=$CORDOVA_TOKEN | jq -r '.apps[].id')"
          if [[ $CORDOVA_APP_ID > 0 ]]
          then
            curl -X DELETE https://build.phonegap.com/api/v1/apps/$CORDOVA_APP_ID?auth_token=$CORDOVA_TOKEN
          fi

          # Phonegap: fix zip upload issue
          cd / && cd usr/local/lib/node_modules/phonegap/node_modules/phonegap-build/lib/phonegap-build/create
          sudo rm zip.js
          curl -O https://raw.githubusercontent.com/phonegap/node-phonegap-build/80e42cb029d133b15026842b10925cab9272ed77/lib/phonegap-build/create/zip.js

          # Phonegap: download iTunes IPA file
          phonegap remote run ios
          phonegap remote run ios > capture_url.txt
          PGB_URL="$(grep -E -o '(http[s]?:\/\/)?([^\/\s]+\/)(.*)' capture_url.txt)"
          wget --user-agent=Mozilla $PGB_URL --output-document=pgb_response_ios.ipa

          ### NOTE TO SELF: 
          # TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
          # with "phonegap remote run ios"





